wandb_version: 1

Architecture:
  desc: null
  value: DINOv2-Self-Supervised
Model:
  desc: null
  value: +reg
Dataset:
  desc: null
  value: Fishency
Batch Size:
  desc: null
  value: 16
Learning_Rate:
  desc: null
  value: 0.00375
Scheduler:
  desc: null
  value: torch.optim.lr_scheduler.StepLR(optimizer, step_size=10, gamma=0.1)
Epochs:
  desc: null
  value: 300
Optimizer:
  desc: null
  value: AdamW(model.parameters(), lr=learning_rate)
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1717008279.0
    t:
      1:
      - 1
      - 41
      - 49
      - 51
      - 55
      2:
      - 1
      - 41
      - 49
      - 51
      - 55
      3:
      - 16
      - 23
      4: 3.9.18
      5: 0.16.4
      8:
      - 1
      - 2
      - 5
      13: linux-x86_64
